### ISSUE TITLE
Error in running findfeatures.py 

### ISSUE THREAD

**Issue by sarahrajabazdeh** [scilearn/FSHDMR#4]
hi , 
i face into this error while trying to run findfeatures.py:
![Screenshot from 2019-07-17 10-37-27](https://user-images.githubusercontent.com/33392969/61351159-1e0d1e80-a87f-11e9-98f9-ec32b117f3ba.png)

**Comment by hkayabilisim** [comment]
Hi,

I need more information to solve the issue:

1. Can you share your previous steps?
2. Are you using your own data or do you use the provided data in data folder?

**Comment by sarahrajabazdeh** [comment]
thank you  for your response, 
i'm using  data provided in reposiotry, 
1- first i make a virtualenv and install prerequirements
2- then i delete whatever have shown in terminal as skipping items(such as Skipping ../results/INDIANPINES_accuracy_chi2_tree.mat
)  
 3-and then try to run findfeatures.py

**Comment by hkayabilisim** [comment]
Thank you. Can I also ask the operating system and python version?

**Comment by sarahrajabazdeh** [comment]
My operating system is ubuntu 18.04 and my python version is 3.6

**Comment by hkayabilisim** [comment]
I'll test it with Ubuntu 18.04 and python 3.6 to see what is going on.

**Comment by sarahrajabazdeh** [comment]
Thank you so much!

**Comment by hkayabilisim** [comment]
It could be related with Python version. Under fresh Ubuntu 18.04 installation, there are both python 2.7 and 3 versions.  I created virtual environment with python3 but findFeatures.py works only with python2.7.

Can you try using python2.7?

**Comment by hkayabilisim** [comment]
I installed a fresh Ubuntu 18.04 and applied the following commands in order to prepare the environment and run FSHDMR. Can you confirm if you are able to run if you follow the same steps?

$ sudo bash
$ apt-get install python2.7 virtualenv   
$ virtualenv -p /usr/bin/python2.7 FSHDMR-env
$ source FSHDMR-env/bin/activate
(FSHDMR-env) root@ubuntu:~# pip -V

	pip 19.1.1 from /home/hkaya/FSHDMR-env/local/lib/python2.7/site-packages/pip (python 2.7)

(FSHDMR-env) root@ubuntu:~# python -V

	Python 2.7.15+

(FSHDMR-env) root@ubuntu:# pip install scipy numpy sklearn joblib
(FSHDMR-env) root@ubuntu:# git clone https://github.com/jundongl/scikit-feature.git
(FSHDMR-env) root@ubuntu:# cd scikit-feature/
(FSHDMR-env) root@ubuntu:/scikit-feature# python setup.py install
(FSHDMR-env) root@ubuntu:/scikit-feature# cd ..
(FSHDMR-env) root@ubuntu:# git clone https://github.com/scilearn/FSHDMR.git
(FSHDMR-env) root@ubuntu:# cd FSHDMR/src/
(FSHDMR-env) root@ubuntu:/FSHDMR/src# python findFeatures.py 

	Skipping ../results/INDIANPINES_features_mrmr.mat
	Skipping ../results/INDIANPINES_features_chi2.mat
	Skipping ../results/INDIANPINES_features_jmi.mat
	Skipping ../results/INDIANPINES_features_infogain.mat
	Skipping ../results/INDIANPINES_features_svmrfe.mat
	...
	Skipping ../results/BOTSWANA_features4c_hdmr.mat
(FSHDMR-env) root@ubuntu:/FSHDMR/src# rm ../results/INDIANPINES_features_chi2.mat
(FSHDMR-env) root@ubuntu:/FSHDMR/src# python findFeatures.py 

	Skipping ../results/INDIANPINES_features_mrmr.mat
	Number of cores: 1
	Obtaining features for robustness chi2 INDIANPINES fold:  0
	[ 28  27  26  29  25  31  24  23  22  32  30  21  20  19  17  18  33  12
	  16  41  40  42  43  47  11  48  44  49  38  15  50  51  46  13  52  14
	  45  10  39  56 115  74 116 114 117   9  34 118 113  53   8  37  54  55
	 119 121 120 112   7 122 124 125 123   6 126  70  69  71  68  73 127 128
	  72  67 129  66 130 131   5  65 132  64  60 133 111  63 134  61 135  62
	 136 137   4 138 160  36 159 139 161 162 163   3 158 153 164 154 148 165
	 166   2 110 167 168 108 157 172 171 140 169  58 173 170  59  57 174 149
	 155 175 156 176   1 177 147 178 152 179 180 181  99 109  35  88 107  98
	 141  97 182 183 100  89 184  91  94   0  81 186 185  75  92 101  93 187
	  84  86  83  76  85  96  80 189 190  95 188  90  82  78  87 146 193 151
	 150 191 192 142 106  77 194  79 196 105 195 197 104 145 102 143 198 144
	 103 199]
	cputime 0.011524
	Obtaining features for robustness chi2 INDIANPINES fold:  1
	...

**Comment by hkayabilisim** [comment]
I assume you tried and solved your problem.

**Comment by sarahrajabazdeh** [comment]
thanks alot for your consideration 
 I create a new virtualenv via python 2 and try agian to run findFeatures.py module and face into this error.
```bash
.
.
.
cputime 553.247384
Number of cores: 8
Obtaining features for robustness chi2 INDIANPINES fold:  0
Obtaining features for robustness chi2 INDIANPINES fold:  1
Obtaining features for robustness chi2 INDIANPINES fold:  2
Obtaining features for robustness chi2 INDIANPINES fold:  3
Traceback (most recent call last):
  File "findFeatures.py", line 124, in <module>
    main()
  File "findFeatures.py", line 28, in main
    find_features(method,dataset,parttype)
  File "findFeatures.py", line 68, in find_features
    results = Parallel(n_jobs=num_cores)(delayed(run_fold)(trial,P,X,y,method,dataset,parttype) for trial in list(range(n_trials)))
  File "/home/aras/codes/Envs/FSHenv/local/lib/python2.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/aras/codes/Envs/FSHenv/local/lib/python2.7/site-packages/joblib/parallel.py", line 862, in retrieve
    raise exception.unwrap(this_report)
joblib.my_exceptions.JoblibAttributeError: JoblibAttributeError
___________________________________________________________________________
...........................................................................
/home/aras/codes/FSHDMR/src/findFeatures.py in <module>()
    119     print features
    120     print 'cputime %f' % cputime
    121     return {'features': features, 'cputime': cputime}
    122 
    123 if __name__ == '__main__':
--> 124     main()

...........................................................................
/home/aras/codes/FSHDMR/src/findFeatures.py in main()
     23     #datasets = {'SUNDIKEN','INDIANPINES','BOTSWANA'}
     24     datasets = {'INDIANPINES','BOTSWANA'}
     25     for dataset in datasets:
     26         for parttype in parttypes:
     27             for method in methods:
---> 28                 find_features(method,dataset,parttype)
        method = 'chi2'
        dataset = 'INDIANPINES'
        parttype = 'robustness'
     29 
     30 def find_features(method,dataset,parttype):
     31     if parttype == 'classification':
     32         outfile='../results/' + dataset + '_features4c_' + method + '.mat'

...........................................................................
/home/aras/codes/FSHDMR/src/findFeatures.py in find_features(method='chi2', dataset='INDIANPINES', parttype='robustness')
     63     features = np.zeros((n_features,n_trials))
     64     cputimes = np.zeros((1,n_trials))
     65 
     66     num_cores = multiprocessing.cpu_count()
     67     print 'Number of cores: %d' % (num_cores)
---> 68     results = Parallel(n_jobs=num_cores)(delayed(run_fold)(trial,P,X,y,method,dataset,parttype) for trial in list(range(n_trials)))
        results = undefined
        num_cores = 8
        trial = undefined
        method = 'chi2'
        dataset = 'INDIANPINES'
        parttype = 'robustness'
        n_trials = 100
     69     for trial in list(range(n_trials)):
     70         result = results[trial]
     71         cputimes[:,trial] = result['cputime']
     72         features[:,trial] = result['features']

...........................................................................
/home/aras/codes/Envs/FSHenv/local/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=Parallel(n_jobs=8), iterable=<generator object <genexpr>>)
    929                 # No need to wait for async callbacks to trigger to
    930                 # consumption.
    931                 self._iterating = False
    932 
    933             with self._backend.retrieval_context():
--> 934                 self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=8)>
    935             # Make sure that we get a last message telling us we are done
    936             elapsed_time = time.time() - self._start_time
    937             self._print('Done %3i out of %3i | elapsed: %s finished',
    938                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Joblib worker traceback:
---------------------------------------------------------------------------
AttributeError                                     Tue Jul 23 12:31:17 2019
PID: 16122       Python 2.7.15rc1: /home/aras/codes/Envs/FSHenv/bin/python2
...........................................................................
/home/aras/codes/Envs/FSHenv/local/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    220     def __call__(self):
    221         # Set the default nested backend to self._backend but do not set the
    222         # change the default number of processes to -1
    223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    224             return [func(*args, **kwargs)
--> 225                     for func, args, kwargs in self.items]
        func = <function run_fold>
        args = (0, memmap([[ 1,  1,  1, ...,  1,  1,  1],
        [...     [ 0,  0,  0, ...,  1,  1,  1]], dtype=int16), memmap([[3196., 3996., 4207., ..., 1021., 1013.,...[4014., 4882., 5406., ..., 1045., 1026., 1015.]]), array([ 1,  1,  1, ..., 16, 16, 16]), 'chi2', 'INDIANPINES', 'robustness')
        kwargs = {}
        self.items = [(<function run_fold>, (0, memmap([[ 1,  1,  1, ...,  1,  1,  1],
        [...     [ 0,  0,  0, ...,  1,  1,  1]], dtype=int16), memmap([[3196., 3996., 4207., ..., 1021., 1013.,...[4014., 4882., 5406., ..., 1045., 1026., 1015.]]), array([ 1,  1,  1, ..., 16, 16, 16]), 'chi2', 'INDIANPINES', 'robustness'), {})]
    226 
    227     def __len__(self):
    228         return self._size
    229 

...........................................................................
/home/aras/codes/FSHDMR/src/findFeatures.py in run_fold(trial=0, P=memmap([[ 1,  1,  1, ...,  1,  1,  1],
        [...     [ 0,  0,  0, ...,  1,  1,  1]], dtype=int16), X=memmap([[3196., 3996., 4207., ..., 1021., 1013.,...[4014., 4882., 5406., ..., 1045., 1026., 1015.]]), y=array([ 1,  1,  1, ..., 16, 16, 16]), method='chi2', dataset='INDIANPINES', parttype='robustness')
     84     if method == 'fisher': 
     85         score = fisher_score.fisher_score(trnX,trnY)
     86         features = fisher_score.feature_ranking(score)
     87     elif method == 'chi2':
     88         score = chi_square.chi_square(trnX,trnY)
---> 89         features = chi_square.feature_ranking(score)
        features = undefined
        score = array([ 47.,  70.,  91.,  99., 108., 122., 137.,... 22.,  14.,  10.,  12.,   9.,
         4.,   1.])
     90     elif method == 'relieff':
     91         score = reliefF.reliefF(trnX,trnY)
     92         features = reliefF.feature_ranking(score)
     93     elif method == 'jmi':

AttributeError: 'module' object has no attribute 'feature_ranking'

```
